### ISSUE TITLE
Version tagged backwards

### ISSUE THREAD

**Issue by agnivade** [splitio/go-split-commons#56]
I am trying to update the dependency of `github.com/splitio/go-client/v6`. We currently have 6.1.0.

But when we try to upgrade, we see this:

```
go get -u github.com/splitio/go-client/v6/...
# github.com/splitio/go-split-commons/v3/service/api/sse
../../go/pkg/mod/github.com/splitio/go-split-commons/v3@v3.1.0/service/api/sse/client.go:50:31: not enough arguments in call to sse.NewClient
        have (string, number, logging.LoggerInterface)
        want (string, int, int, logging.LoggerInterface)
```

Looking into it, it looks like the `go-split-commons` library was indeed updated to match the changes in toolkit. But the version tagged was backwards.

Comparison of 3.1.0 to latest: https://github.com/splitio/go-split-commons/compare/v3.1.0...sselogs/v3

Comparison of 3.0.1 to latest: https://github.com/splitio/go-split-commons/compare/v3.0.1...sselogs/v3

So the real changes are in 3.0.1. However the Go toolchain won't obviously go backward, and therefore we cannot bump the dependency.

Steps to reproduce:
1. clone https://github.com/mattermost/mattermost-server
2. go get -u github.com/splitio/go-client/v6/...

Observe the above failure.

Can we fix the release versions, or perhaps make another release of 3.1.1 pointing to https://github.com/splitio/go-split-commons/commit/9ae876aa8279d38e69d2f5cceb5b59e1615aa0cb?

**Comment by mredolatti** [comment]
Hi @agnivade. Sorry for the hassle. we're currently working on commons-v4, which will includes the fixes in 3.0.1 and will be merged into the next release of `go-client` and `split-synchronizer`. We'll keep you posted on this.
Thank you very much for reaching out and once again, sorry for the inconveniences caused.

Martin.

**Comment by agnivade** [comment]
Thanks @mredolatti. Appreciate it. :)

**Comment by agnivade** [comment]
Hey @mredolatti - apologies for pinging again, just wanted to check if this is planned in the near future?

**Comment by mmelograno** [comment]
Hi @agnivade, we released v4 in November. I will proceed to close the issue.
Please do not hesitate to reopen again if you have any issues.

**Comment by agnivade** [comment]
Wonderful! Thank you @mmelograno

**Comment by danyjacob45** [comment]
This issue popped up in v6.1.0 again.
